language: cpp
compiler: gcc
sudo: require
dist: xenial

install:
  - sudo apt-get -y install cmake libsqlite3-dev libssh-dev libgtk-3-dev libgtk2.0-dev
  - wget -c -nv https://www.4pane.co.uk/temp/wx3.1.tar.xz
  - tar xf wx*.tar.xz
  - sudo dpkg -i *.deb || true # FIXME: Is there a better way to do this and the next line together?
  - sudo apt-get -f install -y

script:
  - wget -c -nv https://www.4pane.co.uk/temp/codelite-13.9-gtk.src.tar.xz
  - tar xf codelite-*-gtk.src.tar.xz
  - cd codelite-*/
  - mkdir -p build-dbg3 && cd build-dbg3/ 
  - cmake -G "Unix Makefiles" VERBOSE=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DWITH_PCH=0 -DCOPY_WX_LIBS=1 ..
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x ./appimagetool-*.AppImage
  - ./appimagetool-*.AppImage deploy appdir/usr/share/applications/*.desktop
  - ./appimagetool-*.AppImage appdir/
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
